export const HANDLE_COLOR = "rgb(224, 151, 4)"
export const HANDLE_COLOR_FOCUSED = "rgb(94, 148, 235)"
export const MODE_ADD_POINT = "ADD_POINT"
export const MODE_DEFAULT = "DEFAULT"
export const MODE_INSERT = "INSERT"